from pathlib import Path

import numpy as np
import sympy as sp

from approachtwo.continuous import (
    analyze as continuous_analyze,
    bode_channel_summary,
)
from approachtwo.allocate import (
    DEFAULT_DAMPING,
    allocated_motor_speeds,
    allocated_squared_speeds,
    create_A,
    pseudoinverse,
    pseudoinverse_equations,
)
from common.geometry import MOTOR_R_Y, MOTOR_R_Z, N_MOTORS
from common.model import inertia_matrix, rigid_body_motion, single_motor_torque


def math_block(expr):
    """Render a SymPy expression as a Markdown math block."""
    return "```math\n" + sp.latex(expr) + "\n```\n"


def code_block(code):
    """Render a Python snippet as a Markdown code block."""
    return "```python\n" + code.strip() + "\n```\n"


def numeric_matrix_block(matrix, decimals=4):
    """Render a rounded numeric matrix as a Markdown math block."""
    rounded = np.round(matrix, decimals)
    rounded[np.isclose(rounded, 0)] = 0

    return math_block(sp.Matrix(rounded))


def markdown_matrix(matrix, row_names=None, col_names=None, precision=4):
    rows = []
    if col_names is not None:
        rows.append("| " + " | ".join([""] + list(col_names)) + " |")
        rows.append("| " + " | ".join(["---"] * (len(col_names) + 1)) + " |")
    for i, row in enumerate(matrix):
        label = row_names[i] if row_names is not None else str(i)
        values = [f"{float(value):.{precision}g}" for value in row]
        rows.append("| " + " | ".join([label] + values) + " |")
    return "\n".join(rows) + "\n"


def geometry_substitutions():
    """Return substitutions for the shared numeric motor geometry."""
    subs = {}
    for motor_index, r_y in enumerate(MOTOR_R_Y):
        subs[f"r_y{motor_index}"] = r_y
    for motor_index, r_z in enumerate(MOTOR_R_Z):
        subs[f"r_z{motor_index}"] = r_z

    return subs


def allocation_matrix_from_equations(active_motors=None):
    """Build the allocation matrix from the same symbolic equations as the sim."""
    if active_motors is None:
        active_motors = [1] * N_MOTORS

    tau_y, tau_z, thrust = rigid_body_motion()
    equations = [
        tau_y.subs(geometry_substitutions()),
        tau_z.subs(geometry_substitutions()),
        thrust,
    ]
    force_symbols = sp.symbols(f"f0:{N_MOTORS}")

    return sp.Matrix(
        [
            [
                sp.expand(equation).coeff(force) * active
                for force, active in zip(force_symbols, active_motors)
            ]
            for equation in equations
        ]
    )


_, _, tau_i = single_motor_torque()
A = allocation_matrix_from_equations()
A_sym = sp.MatrixSymbol("A", 3, N_MOTORS)
w_sq_sym = sp.MatrixSymbol("w^2", N_MOTORS, 1)
u_sym = sp.MatrixSymbol("u", 3, 1)

motor_out_active = [0, 1, 1, 1, 1, 1, 1, 1]
motor_out_A = allocation_matrix_from_equations(motor_out_active)
motor_out_pseudoinverse = pseudoinverse(create_A(motor_out_active))
motor_out_command = (0, 0, 100)
motor_out_w_sq = allocated_squared_speeds(motor_out_command, motor_out_active)
motor_out_w = allocated_motor_speeds(motor_out_command, motor_out_active)
continuous = continuous_analyze()

readme = "<!-- This file is auto-generated by gen_readme.py -->\n"
readme += "# Control Allocation Second Approach\n\n"
readme += """
This approach keeps the same controller inputs as approach one: pitch torque,
yaw torque, and total thrust. The change is that the hand-made quadrant grouping
is gone. Instead, the allocator builds a matrix with one column per motor and
lets the geometry decide how much squared speed each motor should carry.

That is the next natural step because redundancy and failures are per-motor
questions. Once every motor owns a column, disabling a motor is no longer a
special allocation rule; it is just a zeroed or removed column in the same linear
map.

## Building blocks

Each motor still uses the same quadratic propeller model as approach one.
"""
readme += math_block(sp.Eq(sp.Symbol("F_i"), sp.Symbol("C") * sp.Symbol("n_i") ** 2))
readme += "The rigid-body torque expression below is derived by the same SymPy cross product used by the generated simulator.\n"
readme += math_block(sp.Eq(sp.MatrixSymbol(r"\tau_i", 3, 1), tau_i))
readme += (
    "The full inertia matrix is also part of the shared model. The generators "
    "currently substitute unit diagonal values and zero off-diagonal values at "
    "the end, but pitch and yaw rates are first derived through this matrix so "
    "axis coupling is not hidden.\n"
)
readme += math_block(sp.Eq(sp.MatrixSymbol("I", 3, 3), inertia_matrix()))
readme += "The allocator works in squared-speed space because the propeller model is quadratic in speed but linear in squared speed. That choice turns the command vector into a matrix product instead of a nonlinear allocation problem.\n"
readme += math_block(sp.Eq(u_sym, A_sym * w_sq_sym))

readme += """
## Matrix source of truth

The allocation matrix is built from `common.model.rigid_body_motion()` and the
shared geometry constants, not from hand-entered README values. The three rows
are pitch torque, yaw torque, and thrust.
"""
readme += code_block("""
tau_y, tau_z, thrust = rigid_body_motion()
A = allocation_matrix_from_equations()
""")
readme += "With the current shared geometry this expands to:\n"
readme += math_block(sp.Eq(A_sym, A))

readme += """
## Manual pseudoinverse

With more motors than commanded axes, there are many squared-speed vectors that
can produce the same pitch, yaw, and thrust request. The pseudoinverse picks a
least-squares answer from that redundant set. We intentionally do not call
`np.linalg.pinv()` because this approach is meant to show the linear algebra the
allocator is relying on: the code computes the compact SVD and then assembles
the pseudoinverse itself.
"""
for equation in pseudoinverse_equations(A):
    readme += math_block(equation)
readme += """
The strict Moore-Penrose reciprocal is `1 / sigma`. This implementation uses a
singularity-robust reciprocal instead:
"""
readme += math_block(
    sp.Eq(
        sp.Symbol(r"\sigma_{\lambda}^{+}"),
        sp.Symbol(r"\sigma") / (sp.Symbol(r"\sigma") ** 2 + sp.Symbol(r"\lambda") ** 2),
    )
)
readme += (
    f"The default damping is `{DEFAULT_DAMPING}`. Away from singularities this "
    "is effectively the textbook pseudoinverse, but near lost-motor or "
    "rank-deficient cases the reciprocal stays finite.\n"
)

readme += """
## Allocation flow

The allocator multiplies the manually assembled pseudoinverse by the command
vector to get squared motor speeds, then clamps only the final square-root input
so callers never receive imaginary speeds. That clamp is a safety guard for the
return value, not a physical allocation constraint: it does not tell the caller
that the requested command was outside what the motors can really deliver.
"""
readme += code_block("""
w_sq = pseudoinverse(A, damping) @ command
w = tuple(math.sqrt(max(float(speed_sq), 0)) for speed_sq in w_sq.flatten())
""")
readme += (
    "`gen_allocate.py` writes these runtime allocation functions into "
    "`allocate.py`; `model.py` imports that generated module so the generated "
    "allocator is the source used by the rest of approach two.\n"
)

readme += """
## Continuous-time analysis of the generated loop

Approach two uses the same shared state-space analysis helpers as approach one,
but the linearization is now backed by the per-motor pseudoinverse allocator.
The hover trim remains the same command/state pair, while the motor trim is a
least-squares per-motor squared-speed solution:
"""
readme += code_block(f"""
trim_command = {tuple(float(x) for x in continuous.trim_command)}
trim_state = {tuple(float(x) for x in continuous.trim_state)}
trim_motor_speeds = {tuple(round(float(x), 4) for x in continuous.motor_trim)}
""")
readme += "The local command-to-output gain matrix is computed from the generated `allocate -> sim` loop.\n"
readme += markdown_matrix(
    continuous.command_jacobian,
    ["pitch rate q", "yaw rate r", "airspeed u"],
    ["tau_y", "tau_z", "T"],
)
readme += "\n"
readme += "| channel | local transfer function |\n| --- | --- |\n"
for channel, tf in bode_channel_summary(continuous):
    readme += f"| {channel} | `{tf}` |\n"
readme += f"""

The state-space model keeps pitch and yaw as integrators and uses a first-order
airspeed lag with the stack-derived static gain. The closed-loop eigenvalues are
`{tuple(round(float(x.real), 4) for x in continuous.loop_eigenvalues)}`, so the
local verdict is **{continuous.stability_verdict}**.

The local controllability rank is `{continuous.controllability_rank}` and the
observability rank is `{continuous.observability_rank}`. In approach two this is
more meaningful than the quadrant result because the allocation matrix exposes
each motor column before the state-space summary is assembled.

Robustness notes from the analysis:

"""
for note in continuous.robustness_notes:
    readme += f"- {note}\n"
readme += """

These Bode and rank checks are still local, unconstrained analyses. They explain
the hover loop and motor-out matrix intuition, but approach three is still needed
for hard speed limits and attainable-set margins.
"""

readme += """
## Motor-out example

To make the benefit of the matrix form concrete, the generator also runs a
motor-out case with motor 0 disabled. The motor-out allocation matrix is derived
from the same symbolic equations, then the inactive motor mask zeroes the failed
motor column:
"""
readme += math_block(sp.Eq(A_sym, motor_out_A))
readme += (
    "The pseudoinverse matrix below is computed from that real motor-out "
    "allocation matrix and is the actual matrix used to produce squared-speed "
    "commands. Row 0 is all zeros, so the failed motor receives no command.\n"
)
readme += "The actual `A_plus` motor-out matrix is:\n"
readme += numeric_matrix_block(motor_out_pseudoinverse)
readme += (
    "For any command vector `u`, the allocator computes `w_sq = A_plus @ u` "
    "from this matrix and then square-roots the non-negative entries. For "
    "example, with `u = [0, 0, 100]` the squared-speed command is:\n"
)
readme += numeric_matrix_block(motor_out_w_sq)
readme += "and the final motor-speed command is:\n"
readme += numeric_matrix_block(np.array(motor_out_w).reshape(N_MOTORS, 1))

readme += """

## Why this is not enough

The matrix allocator is more general than the quadrant allocator: it uses every
motor independently, and a motor-out case is handled by changing the active
columns rather than writing a new control law. But it is still an unconstrained
least-squares solution. The pseudoinverse can request negative squared speeds or
speeds above the physical motor limit. Clamping before the square root keeps the
returned speeds real, but it silently changes the command and hides which
attitude or thrust target was sacrificed. Approach three makes those physical
bounds part of the optimization problem instead of repairing the answer after
the fact.
"""

with open(Path(__file__).with_name("README.md"), "w") as f:
    f.write(readme)
