from pathlib import Path

import sympy as sp

from common.geometry import MOTOR_R_Y, MOTOR_R_Z, N_MOTORS
from approachone.continuous import (
    analyze as continuous_analyze,
    bode_channel_summary,
    save_bode_plot,
)
from common.model import rigid_body_motion


def math_block(expr):
    """Render a SymPy expression as a Markdown math block."""
    return "```math\n" + sp.latex(expr) + "\n```\n"


def code_block(code):
    """Render a Python snippet as a Markdown code block."""
    return "```python\n" + code.strip() + "\n```\n"


r_i = sp.Symbol(r"\mathbf{r_i}")
F_i = sp.Symbol(r"\mathbf{F_i}")
tau_i = sp.Symbol(r"\boldsymbol{\tau_i}")
T = sp.Symbol("T")
C_T, rho, n_i, D, C = sp.symbols(r"C_T \rho n_i D C")

total_thrust = sp.Eq(T, sp.Sum(sp.Symbol("F_i"), (sp.Symbol("i"), 0, N_MOTORS - 1)))
prop_thrust = sp.Eq(F_i, C_T * rho * n_i**2 * D**4)
simplified_prop_thrust = sp.Eq(F_i, C * n_i**2)

force_symbols = sp.symbols(f"f0:{N_MOTORS}")
tau_y, tau_z, thrust = rigid_body_motion()
force_subs = {f"f{i}": force_symbols[i] for i in range(N_MOTORS)}
geometry_subs = {}
for motor_index, r_y in enumerate(MOTOR_R_Y):
    geometry_subs[f"r_y{motor_index}"] = r_y
for motor_index, r_z in enumerate(MOTOR_R_Z):
    geometry_subs[f"r_z{motor_index}"] = r_z

expanded_tau_y = tau_y.subs(force_subs).subs(geometry_subs)
expanded_tau_z = tau_z.subs(force_subs).subs(geometry_subs)
expanded_thrust = thrust.subs(force_subs)
continuous = continuous_analyze()
bode_plot_path = Path(__file__).with_name("assets") / "continuous_bode.png"
save_bode_plot(continuous, bode_plot_path)


def markdown_matrix(matrix, row_names=None, col_names=None, precision=4):
    rows = []
    if col_names is not None:
        rows.append("| " + " | ".join([""] + list(col_names)) + " |")
        rows.append("| " + " | ".join(["---"] * (len(col_names) + 1)) + " |")
    for i, row in enumerate(matrix):
        label = row_names[i] if row_names is not None else str(i)
        values = [f"{float(value):.{precision}g}" for value in row]
        rows.append("| " + " | ".join([label] + values) + " |")
    return "\n".join(rows) + "\n"


readme = "<!-- This file is auto-generated by gen_readme.py -->\n"
readme += "# Control Allocation First Approach\n\n"
readme += """
This approach is intentionally simple: it groups the eight motors into four
quadrants instead of allocating against each motor independently. That is the
first useful approximation because it makes the mapping from pitch torque, yaw
torque, and total thrust to motor commands easy to inspect by hand. The allocator
turns each command into rotor-speed contributions and sums those commanded rotor
speeds per quadrant, while the simulator still applies the per-motor geometry to
predict the resulting rates and airspeed.

The tradeoff is that the allocator has deliberately hidden some reality. Paired
motors are treated as one actuator group, so individual motor authority,
asymmetric limits, and motor failures are not first-class concepts yet. That is
why approach two removes the quadrant shortcut and exposes every motor as its own
allocation variable.

## Building blocks

At the highest level, each motor contributes torque from a moment arm crossed
with its thrust force.
"""
readme += (
    "```math\n"
    + sp.latex(tau_i)
    + r" = "
    + sp.latex(r_i)
    + r" \times "
    + sp.latex(F_i)
    + "\n```\n"
)
readme += "The total thrust is the sum of all motor thrusts.\n"
readme += math_block(total_thrust)
readme += "Each propeller is modeled with the usual quadratic thrust relationship, then collapsed into a single coefficient used by the generated code.\n"
readme += math_block(prop_thrust)
readme += math_block(simplified_prop_thrust)

readme += """
## SymPy source of truth

The generator scripts keep the math symbolic first. The rigid-body model builds
symbolic torque and thrust equations, then the generation steps substitute the
shared geometry constants from `common.geometry` before printing Python or LaTeX.
"""
readme += code_block("""
from common.geometry import MOTOR_R_Y, MOTOR_R_Z
from common.model import rigid_body_motion

tau_y, tau_z, thrust = rigid_body_motion()
# gen_sim.py substitutes MOTOR_R_Y and MOTOR_R_Z into these symbolic equations.
""")

readme += "The generated simulator uses these symbolic equations for pitch rate, yaw rate, and airspeed.\n"
readme += math_block(sp.Eq(sp.Symbol(r"\dot{q}"), tau_y))
readme += math_block(sp.Eq(sp.Symbol(r"\dot{r}"), tau_z))
readme += math_block(sp.Eq(T, expanded_thrust))

readme += """
## Allocation flow

The allocator starts by splitting thrust between the negative-`r_z` and
positive-`r_z` motor rows so a pure thrust request does not accidentally create a
pitch torque. It then adds signed speed deltas for yaw torque by quadrant. Each
quadrant arm is the average position of its two motors. This is a design choice:
it makes the first allocator small and readable, but it assumes the two motors in
a quadrant can be commanded as a pair. Shared quadrant geometry constants are
substituted during generation so runtime callers only pass the three commands
and `C`.
"""
readme += code_block("""
w = allocated_motor_speeds(tau_y, tau_z, thrust, C, r_quadrant_y, r_quadrant_z)
# gen_allocate.py substitutes ALLOCATION_R_QUADRANT_Y/Z before writing allocate.py.
""")

readme += """
## Example expanded equations

After substituting the current approach-one motor geometry, the compact vector
math expands into concrete linear combinations of motor thrusts. These expanded
forms are what the generated simulator ultimately evaluates.
"""
readme += math_block(sp.Eq(sp.Symbol(r"\tau_y"), expanded_tau_y))
readme += math_block(sp.Eq(sp.Symbol(r"\tau_z"), expanded_tau_z))

readme += """
## Continuous-time analysis of the generated loop

The continuous-time view is computed from the runnable approach-one stack rather
than from a separate hand model. `approachone.continuous.analyze()` linearizes the
actual `allocate -> sim` path about the hover trim, then wraps that local plant in
a compact state-space model for Bode, controllability, stability, robustness, and
observability discussion. The trim command and state are:
"""
readme += code_block(f"""
trim_command = {tuple(float(x) for x in continuous.trim_command)}
trim_state = {tuple(float(x) for x in continuous.trim_state)}
trim_motor_speeds = {tuple(round(float(x), 4) for x in continuous.motor_trim)}
""")
readme += "The local command-to-output gain matrix uses continuous units for pitch and yaw rows and static gain for airspeed.\n"
readme += markdown_matrix(
    continuous.command_jacobian,
    ["pitch rate q", "yaw rate r", "airspeed u"],
    ["tau_y", "tau_z", "T"],
)
readme += "\nFor classical Bode intuition, the diagonal channels reduce to these local transfer functions:\n\n"
readme += "![Approach one continuous-time Bode plot](assets/continuous_bode.png)\n\n"
readme += "| channel | local transfer function |\n| --- | --- |\n"
for channel, tf in bode_channel_summary(continuous):
    readme += f"| {channel} | `{tf}` |\n"
readme += f"""

The corresponding state-space plant uses the rate axes as integrators and models
the airspeed channel as a first-order lag with the static thrust-to-airspeed gain
reported above. With the documented sign-aware diagonal proportional gains, the
closed-loop eigenvalues are `{tuple(round(float(x.real), 4) for x in continuous.loop_eigenvalues)}`, so the local verdict is **{continuous.stability_verdict}**.

Controllability and observability are both full rank for this three-state local
model: controllability rank `{continuous.controllability_rank}` and observability
rank `{continuous.observability_rank}`. That means the abstract pitch, yaw, and
airspeed channels can be independently moved and seen near the trim point. It
does **not** mean approach one is robust to hardware failures; the quadrant
allocator has already hidden the individual motor degrees of freedom.

Robustness notes from the analysis:

"""
for note in continuous.robustness_notes:
    readme += f"- {note}\n"
readme += """

The important limitation is the yaw nonlinearity: approach one commands signed
`sqrt(abs(tau_z))` deltas, so the exact derivative at zero yaw command is not a
well-behaved linear slope. The generated table therefore reports a small
finite-difference slope for stack-level documentation, while later approaches
replace this shortcut with allocation matrices that are better suited to formal
controllability and robustness analysis.
"""

readme += """
## Why this is not enough

This version is valuable because every step is visible: thrust and pitch are
balanced across the two `r_z` rows, yaw adds signed quadrant corrections, and the
simulator shows the resulting motion. But the simplicity comes from a hand
grouping that throws away per-motor freedom. It cannot naturally ask what
happens when one motor fails, whether one motor should work harder than its
neighbor, or whether a redundant set of motors is being used optimally. Approach
two keeps the same command interface but replaces the quadrant rule with a
geometry-derived matrix that has one column per motor.
"""

with open(Path(__file__).with_name("README.md"), "w") as f:
    f.write(readme)
